# Generated by Django 6.0.5 on 2026-05-27 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('institucion', models.CharField(max_length=150, verbose_name='Institución')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('actualmente', models.BooleanField(default=False, verbose_name='Trabajo Actual')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-actualmente', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tecnologias', models.CharField(max_length=300, verbose_name='Tecnologías')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen')),
                ('enlace_github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('enlace_demo', models.URLField(blank=True, null=True, verbose_name='Demo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha'],
            },
        ),
    ]
