# Generated by Django 6.0.5 on 2026-06-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_educacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='enlace_repo',
            field=models.URLField(blank=True, null=True, verbose_name='Reposiorio'),
        ),
    ]
