# Generated by Django 6.0.5 on 2026-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proyecto_enlace_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Curriculum Vitae', max_length=100)),
                ('archivo', models.FileField(upload_to='cv/', verbose_name='Archivo PDF')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum Vitae',
                'verbose_name_plural': 'Curriculum Vitae',
            },
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enlace_repo',
            field=models.URLField(blank=True, null=True, verbose_name='Repositorio'),
        ),
    ]
